### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by darklinkpower** [mattiadr/MALstreaming#1]
I have installed the script since the features look pretty useful, but for some reason it's not modifying anything in my list. I've checked and the script is enabled. Any idea why this might be happening? Also using the css didn't work and it didn't make the list like yours.

https://i.imgur.com/fNP3gQ2.png
https://i.imgur.com/8DbSJxj.jpg
thanks in advance and thanks for making the script.

**Comment by mattiadr** [comment]
Thank you for checking out the script!

From the second image it looks like you are using the old MAL design, you can change it in your settings -> List Style Design.
You have to set the design to modern and then default theme (https://i.imgur.com/GS6aLEY.png).
After you save you can click on the center of the default theme and it will open the theme editor, finally copy and paste the css in the appropriate section on the left (https://i.imgur.com/EyS6Sdl.png) and save.

Also if you are using firefox and still having issues you should install the [tampermonkey extension for firefox](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) (instead of greasemonkey). The first versions of the script worked with greasemonkey, but now the script is using features only available on tampermonkey and I forgot to update the README.

Let me know if this solves it! Thanks.

**Comment by darklinkpower** [comment]
Thanks for the quick reply.
You were right, I was using the old mal style.

I use violent monkey on firefox but I just installed tampermonkey and the script but it's not adding the column, is there an extra step to get it? I disabled all other addons in case something was conflicting and I tried in two different devices but the column is not getting added

https://i.imgur.com/mTJFSCD.png

**Comment by mattiadr** [comment]
This is stange... it should not require additional steps.
I just installed firefox and it works for me.
Do you have the latest version of firefox?
You can check it by going in menu > help > about firefox.
A window like this (https://i.imgur.com/YHVYNok.png) should pop up, latest version is 67.0.1

**Comment by darklinkpower** [comment]
Yeah exactly that version. I'll try now on chrome to see how it goes

**Comment by darklinkpower** [comment]
I can confirm it's working in chrome, I see you updated the script but the new version isn't working in my firefox still.

Also for some reason I'm not getting results in any manga or anime in any site (No Results. Try changing the title in the search box above."), I gave the needed permissions in tampermonkey. I checked even if it was using the exact same series name but no luck :(

edit: now I'm getting some results, but for example, I can't find Birdmen in mangadex, even though it's in the site https://mangadex.org/title/9679/birdmen

edit2: now it's working in firefox, forgot I had disabled it my bad. Still have the issue of no results for mangadex though but thanks for the update

**Comment by mattiadr** [comment]
I'm glad you got it working on firefox!

I think I know why you can't find anything on mangadex.
If you try to search on the website for a manga without having an account it will give this warning: "Notice: Certain features disabled for guests during DDoS mitigation."
You can create an account, log in and it should work or you can insert the series manually instead of using the search function.

To insert something manually you have to write `mangadex ID` inside the comment box, for example for birdmen `mangadex 9679`. You can find this id in the url address of the corresponding page (https://mangadex.org/title/9679/birdmen).

On mangadex there is another issue: since they offer chapters in multiple languages all in the same page you need to filter only the ones in the language you want to read otherwise they might get mixed up. I don't think you need to login to filter chapters.

There are issues with 9anime search too, you can insert it manually like this:
https://www1.9anime.nl/watch/attack-on-titan.kww -> `nineanime attack-on-titan.kww`.

It works in a similar way for all the other websites, you put the website name and then the last part of the url.
Here are all the names if you need them: `kissanime, nineanime, animetwist, kissmanga, mangadex, jaiminisbox`.

I will fix the search for 9anime soon hopefully.

If you have other issues feel free to ask :)

**Comment by darklinkpower** [comment]
That's weird, I'm logged in mangadex. There's something I just saw in firefox: although the column is showing up, no content is displayed in it

![imagen](https://user-images.githubusercontent.com/1389286/59231160-4aa98880-8ba5-11e9-88eb-e163dc28bf4a.png)

For example, in chrome I get a No link or the link if it has been added but nothing in firefox.
Chrome: 
![imagen](https://user-images.githubusercontent.com/1389286/59231131-349bc800-8ba5-11e9-9c46-20580d4b44d8.png)

**Comment by mattiadr** [comment]
That's weird...

Can you send me the console log?
You can open the dev tools by pressing `ctrl+shift+i`, then select the console tab, try to reload the page and then send me the output with https://pastebin.com/.
Also try clicking on the watch column header or the cells in that column, it should retry to get the episodes.

I will look at the console output in the morning.

**Comment by darklinkpower** [comment]
Ok I just checked and it works if I use Tampermonkey instead of Violentmonkey. 
Does it use tampermonkey specific functions to work then? I know greasemonkey has lagged behind but I didn't know it was better than violentmonkey

**Comment by mattiadr** [comment]
I have never used Violetmonkey, but taking a quick look at their documentation seems like it's missing a couple of function I'm using (`GM_addValueChangeListener` and `GM_removeValueChangeListener`).
They are used to automatically load cookies for websites that require them.
Also I didn't expect the script to not work at all if it wasn't able to find those functions, I will try to make it work anyway in the future (maybe by disabling the cookies functionality if you don't have tampermonkey).

**Comment by darklinkpower** [comment]
Awesome and thanks again for all the help

**Comment by mattiadr** [comment]
Glad I could help :)
