### ISSUE TITLE
Script breaks after 150 titles

### ISSUE THREAD

**Issue by darklinkpower** [mattiadr/MALstreaming#2]
I just noticed that after 150 titles, the Read column is not applied.
![imagen](https://user-images.githubusercontent.com/1389286/59285614-dcf86d80-8c33-11e9-9c63-7d158ba56c80.png)

Also I don't know the exact number, but the script is just adding a "Not yet published" to every title, even if it has the url id in the comments. For it to apply, I need to filter it with tags to bring the list to less numbers.

No filtering:
![imagen](https://user-images.githubusercontent.com/1389286/59285813-36609c80-8c34-11e9-94f0-e522f025c003.png)

Filtered:
![imagen](https://user-images.githubusercontent.com/1389286/59285877-51331100-8c34-11e9-8bf2-105a48ee157a.png)

I think it's related too to the number of titles in the current view.

**Comment by mattiadr** [comment]
If I remember correctly, when you initially load a list on MAL it will only show a few elements and when you scroll down it will then load the rest.
The scripts inserts the "read" cells only when the list loads the first time, so that's why after 150 titles it stops.
I will look into it, but as I wrote in issue #3 I need a longer list to test the script.

**Comment by mattiadr** [comment]
Version 5.37 (5be54d0) should fix this issue.
Sometimes when trying to load more then 300 titles the cells were not loaded, but I haven't found a way to consistently reproduce it.

If this works for you too feel free to close this issue.

**Comment by darklinkpower** [comment]
I can confirm that the script is no longer breaking after 150 titles
