### ISSUE TITLE
Too many requests! (Mangadex)

### ISSUE THREAD

**Issue by darklinkpower** [mattiadr/MALstreaming#3]
After using the script in a filter list with around 25 titles, around half of them didn't load the chapter count
![imagen](https://user-images.githubusercontent.com/1389286/59286179-e0d8bf80-8c34-11e9-9a62-1f43520d8700.png)

Upon entering mangadex I was greeted with this message
![imagen](https://user-images.githubusercontent.com/1389286/59286071-acfd9a00-8c34-11e9-97bd-5d8407c0f78e.png)

It occurs to me that maybe this could be fixed if there was a request delay to sent the request to mangadex because with the recend DDoS attacks to them they have implemented this. Another option could be to just add links to the chapter list next to the titles just using the ID number without sending an actual request to mangadex,

And I don't know if it's possible, but could it be possible to store the chapter data locally to not send request each time you visit your list to prevent this and just update them when you maybe hit a button?  I don't know just throwing ideas because I don't know anything about coding tbh

**Comment by mattiadr** [comment]
I searched the mangadex api and unfortunately I could not find much about request limits.
The only thing I found is this post on [reddit](https://redd.it/9z3i6u), but it's from before the DDoS attacks so they may have reduced the limit it because the script makes only 1 request per title, so it's unlikely to have hit the 1500/10 mins limit.
The easy fix is to implement a delay, or disable automatic requests if the list exceeds a certain size.

Unfortunately I have never tried this with lists longer then 15 elements, so I need to create a new account and do some testing. If it is not a problem for you, could you export your list and send a copy to me? It will help me test stuff faster.

Storing the title data locally is another option, I will think about it.
Since I'm busy with exams at the moment, the local storage will probably take longer.

**Comment by mattiadr** [comment]
Version 5.37 (5be54d0) might mitigate this too.
If you still have issues please let me know.

**Comment by darklinkpower** [comment]
I tried the script again and sadly it's banning again. It should be difficult to solve this thanks to their DDoS protection, like you said, maybe disable automatic requests is the solution.

**Comment by mattiadr** [comment]
As a temporary measure the script now stops after 15 requests to a single website.

In the future I will implement a cache to avoid requesting the chapter list every time.
We should keep this issue open until that's done.

**Comment by mattiadr** [comment]
Version 5.47 (2815482) implemented a queue for all requests instead of stopping after 15, this should avoid bans on every website.
The default value is 2 requests every second.
