### ISSUE TITLE
It stucks on Searching..

### ISSUE THREAD

**Issue by ghost** [mattiadr/MALstreaming#4]
When i try to use Search button, i selected first 9anime it says no results found anime twist too. I tried kissanime it stucks on searching for a while.

**Comment by mattiadr** [comment]
Anime twist should work, you just need to try with both the english and japanese title. For example you can search for "My Hero Academia" and "Boku no Hero Academia", one of the two should work.

Kissanime and 9anime need to be fixed since they changed how the search page works. I will fix it as soon as I can.

**Comment by mattiadr** [comment]
Kissanime and 9anime should be fixed now!
